### ISSUE TITLE
Known Bugs

### ISSUE THREAD

**Issue by mfalt** [JuliaControl/ControlSystems.jl#151]
We can use this issue to keep track of known bugs, issues and the progress we are making after pulling the major autodiff branch

Bugs
- [ ] `pole` for mimo system, should not return duplicates, see https://github.com/JuliaControl/ControlSystems.jl/issues/81
- [ ] `dampreport` fails on complex poles
- [ ] `minreal` will throw error for Integer systems if poles are not exact integers see https://github.com/JuliaControl/ControlSystems.jl/issues/127
- [ ] `feedback2dof` silently breaks for discrete systems see https://github.com/JuliaControl/ControlSystems.jl/issues/95
- [ ] call on discrete system with freq vector ignores "map_to_unit_circle" Fixed: 
- [ ] Systems can have negative sample time (used for "unspecified sample time"), makes iscontinuous true, results in bugs in evalfr

Type problems
- [ ] `c2d` of `TransferFunction{SisoZpk}` returns ``TransferFunction{SisoRational}`

Other issues
- [ ]  Tests for plots are deactivated for now 
- [ ]  `c2d` not working for improper transfer functions, see https://github.com/JuliaControl/ControlSystems.jl/issues/128
- [ ] Multiple "TODO" in code needs to be be checked
